// Code generated by mockery v2.42.2. DO NOT EDIT.

package postgresmocks

import (
	context "context"

	postgres "github.com/kenyako/platform_common/pkg/postgres"
	mock "github.com/stretchr/testify/mock"
)

// TxManager is an autogenerated mock type for the TxManager type
type TxManager struct {
	mock.Mock
}

// ReadCommitted provides a mock function with given fields: ctx, f
func (_m *TxManager) ReadCommitted(ctx context.Context, f postgres.Handler) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ReadCommitted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.Handler) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxManager creates a new instance of TxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxManager {
	mock := &TxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
